# Generated by Django 5.1.3 on 2024-11-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_alter_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
