# Generated by Django 5.1.3 on 2024-11-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_alter_category_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
